authors:
  masonegger:
    name: Mason Egger
    description: Developer, Educator, Community Organizer
    avatar: https://github.com/masonegger.png
  thejcannon:
    name: Josh Cannon
    description: "Josh is an avid lover of tooling that accelerates developers, including being a maintainer of the Polyglot Open-Source Build System: Pants. In his free time, Josh enjoys laser cutting/engraving and his wonderful family."
    avatar: https://github.com/thejcannon.png
  charliermarsh:
    name: Charlie Marsh
    description: "Building astral-sh: high-performance developer tools for Python, starting with Ruff."
    avatar: https://github.com/charliermarsh.png
  dijital20:
    name: Josh Schneider
    description: Test Automation Architect, Python nerd, Improv comedy nerd, father, drinker of coffee, and quoter of movies.
    avatar: https://github.com/dijital20.png
  mariatta:
    name: Mariatta
    description: Mariatta is a Python core developer where she focuses on improving the workflow and documentation. She is active in the Python community as an advisor for the Global PyLadies, co-founder of PyCascades, and is currently chairing PyCon US conference.
    avatar: https://github.com/mariatta.png
  automationpanda:
    name: Pandy Knight
    description: I'm the Automation Panda! I build solutions to testing problems.
    avatar: https://github.com/automationpanda.png
  asweigart:
    name: Al Sweigart
    description: Author of Automate the Boring Stuff with Python and other programming books
    avatar: https://github.com/asweigart.png
  pathunstrom:
    name: Piper Thunstrom
    description: Pythonista, Game Enthusiast, and Web Developer
    avatar: https://github.com/pathunstrom.png
  kukicado:
    name: Ado Kukic
    description: Full-Stack Engineer, DevRel Leader at SourceGraph
    avatar: https://github.com/adocomplete.png
  darkbeast-glitch:
    name: Julius Boakye
    description: Software Engineer with Proficiency in Python Django, Flutter and Dart.
    avatar: https://avatars.githubusercontent.com/u/66005635?v=4
  moshez:
    name: Moshe Zadka
    description: Twisted & Python contributor. Loves infrastructure and SRE.
    avatar: https://github.com/moshez.png
  zviboshernitzan:
    name: Zvi Boshernitzan
    description: Software engineer and technologist based in Austin.
    avatar: assets/images/ZviBoshernitzan.jpg
  marissaskudlarek:
    name: Marissa Skudlarek
    description: Marissa Skudlarek is a Senior Software Engineer at Lex Machina and an accomplished playwright and translator.
    avatar: assets/images/MarissaSkudlarek.jpg
  jimvogel:
    name: Jim Vogel
    description: Jim Vogel, Lead Architect at Gravitate, brings two decades of software development experience and currently works in the oil and gas industry.
    avatar: https://vogelcc.com/headshot_2023.jpg
  marcelosacchetin:
    name: Marcelo Sacchetin
    description: Marcelo Sacchetin has been helping software developers over a decade to write secure code across multiple start-ups and Fortune 500 companies. He mainly focuses on building automation for SDL and empowering developers to master cybersecurity.
    avatar: https://images.squarespace-cdn.com/content/v1/5a60c2ed017db2e8dedb82b7/1596464328366-LATX12LSPIG51T2W4QF5/Marcelo.jpg
  lawrenceallanjones:
    name: Lawrence Allan Jones
    description: Software Architect with over 10 years experience architecting, building, and maintaining complex applications. Designed and developed retail web applications, internal web applications for a multi-national company, seismic processing on computing clusters, and desktop applications with near-real-time data streams.
    avatar: assets/images/LawrenceAllanJones.jpg
  jonathanscofield:
    name: Jonathan Scofield
    description: Jonathan Scofield is a data analyst and engineer in the music publishing industry. He regularly uses Pandas, Polars, and PySpark to build pipelines for asset metadata and transaction reports. Jonathan's journey with Polars began a year ago when he needed to migrate data between an on-premise database and a cloud-based solution. His entire team was awed by its rare combination of speed, flexibility, and simplicity. Since then, Polars has been a vital tool in his data toolbox and will continue to be for the foreseeable future. When he is not geeking out about data, he enjoys playing the piano and attempting to learn Mandarin.
    avatar: https://jonathanscofield1.github.io/jonathanscofield/images/profile.png
  dishantsethi:
    name: Dishant Sethi
    description: I’m Dishant! I’m a computer science graduate with over 5 years of experience in software development, cloud infrastructure, and AI/ML pipelines. I’ve had the opportunity to work with a few early-stage startups in Boston and New York, providing software consultancy. These days, I’m focused on building AI applications, helping teams solve technical challenges and build scalable solutions. When I’m not working on tech, you’ll probably find me in the kitchen, experimenting with new recipes. Feel free to reach out if you would like to talk about product engineering, AI, or cooking.
    avatar: https://avatars.githubusercontent.com/u/31399916
  souravsaha:
    name: Sourav Saha
    description: Sourav has 11 years of professional experience at NEC Corporation, Japan in the diverse fields of High-Performance Computing, Distributed Programming, and Data Science. He holds a bachelor’s degree in Computer Science and is currently affiliated with the Digital Technology Development Laboratories at NEC as a Senior Research Engineer. Blending the mixture of different niche technologies related to compiler framework, high performance computing, and multi-threaded programming, his team is developing a high-performance compiler accelerated DataFrame library, named FireDucks. He is mostly passionate about program optimization, public speaking and has been speaking in several technical conferences, meetups etc.
    avatar: assets/images/Sourav_Saha.jpg
  pavanreddy:
    name: Pavan Reddy
    description: Pavan earned his M.S. in Computer Science from George Washington University, where he also served as a teaching assistant, delivering lectures on Computer Vision concepts in the context of Augmented Reality (AR) and Virtual Reality (VR).
    avatar: assets/images/PavanReddy.jpeg
    pavanreddy:
  akshaymittal:
    name: Akshay Mittal
    description: Akshay Mittal is a seasoned IT professional with over a decade of experience as a full-stack developer and a growing footprint in technology leadership. He currently serves as a Staff Software Engineer at PayPal, where he builds scalable, resilient systems in high-performance cloud environments. In parallel, Akshay is pursuing a PhD at the University of the Cumberlands, focusing his research on the convergence of cloud-native architectures and AI/ML-driven automation.
    avatar: assets/images/AkshayMittal.jpeg
  jefftriplett:
    name: Jeff Triplett
    description: Data Leader for Emerging Technologies, transforming enterprises with latest trending AI/ML technologies.
    avatar: assets/images/jeff.jpg
  landonjurgens:
    name: Landon Jurgens
    description: Software developer working in Python since 2008.
    avatar: assets/images/landon-jurgens.jpg
  miguelvargas:
    name: Miguel Vargas
    description: Miguel Vargas is a software engineer with over 10 years of experience in front-end and back-end development, working with Python and TypeScript. He has collaborated with startups across industries such as finance, healthcare, real estate, and logistics, helping them scale their platforms with clean, reliable, and secure code. Currently, he works at Moxie, a health-tech startup.
    avatar: assets/images/miguel.jpg
  advityagemawat:
    name: Advitya Gemawat
    description: Advitya is an ML Engineer at Microsoft, specializing in scalable machine learning systems and Responsible AI. He has authored publications, holds patents, and received awards from leading venues such as VLDB, ACM SIGMOD, and CIDR.
    avatar: assets/images/advitya.jpg
