authors:
  masonegger:
    name: Mason Egger
    description: Developer, Educator, Community Organizer
    avatar: https://github.com/masonegger.png
  thejcannon:
    name: Josh Cannon
    description: "Josh is an avid lover of tooling that accelerates developers, including being a maintainer of the Polyglot Open-Source Build System: Pants. In his free time, Josh enjoys laser cutting/engraving and his wonderful family."
    avatar: https://github.com/thejcannon.png
  charliermarsh:
    name: Charlie Marsh
    description: "Building astral-sh: high-performance developer tools for Python, starting with Ruff."
    avatar: https://github.com/charliermarsh.png
  dijital20:
    name: Josh Schneider
    description: Test Automation Architect, Python nerd, Improv comedy nerd, father, drinker of coffee, and quoter of movies.
    avatar: https://github.com/dijital20.png
  mariatta:
    name: Mariatta
    description: Mariatta is a Python core developer where she focuses on improving the workflow and documentation. She is active in the Python community as an advisor for the Global PyLadies, co-founder of PyCascades, and is currently chairing PyCon US conference.
    avatar: https://github.com/mariatta.png
  