masonegger:
  name: Mason Egger
  description: Developer, Educator, Community Organizer
  avatar: https://github.com/masonegger.png
josh-schneider:
  name: Josh Schneider
  description: Test Automation Architect, Python nerd, Improv comedy nerd, father, drinker of coffee, and quoter of movies.
  avatar: https://github.com/dijital20.png
